/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author Osiris Robledo
 */
public class AccountDetailsPage extends javax.swing.JDialog {

    /**
     * Creates new form AccountDetailsPage
     */
    public AccountDetailsPage(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        firstNameField.setText(customer.getFirstName());
        lastNameField.setText(customer.getLastName());
        ssnField.setText(customer.getSsn());
        typeField.setText(customer.getAccountType());
        accountNumberField.setText(String.valueOf(customer.getAcc()));
        balanceField.setText(String.format("$%.2f", customer.getBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        ssnField = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JLabel();
        accountNumberLabel = new javax.swing.JLabel();
        accountNumberField = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        balanceField = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Information");
        setPreferredSize(new java.awt.Dimension(380, 375));
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 5, 5));

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstNameLabel.setText("First Name:");
        getContentPane().add(firstNameLabel);

        firstNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(firstNameField);

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastNameLabel.setText("Last Name:");
        getContentPane().add(lastNameLabel);

        lastNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lastNameField);

        ssnLabel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        ssnLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ssnLabel.setText("SSN:");
        getContentPane().add(ssnLabel);

        ssnField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ssnField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ssnField);

        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        typeLabel.setText("Account Type:");
        getContentPane().add(typeLabel);

        typeField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        typeField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(typeField);

        accountNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        accountNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accountNumberLabel.setText("Account Number:");
        getContentPane().add(accountNumberLabel);

        accountNumberField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        accountNumberField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(accountNumberField);

        balanceLabel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balanceLabel.setText("Balance:");
        getContentPane().add(balanceLabel);

        balanceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(balanceField);

        returnButton.setText("Back");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumberField;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JLabel balanceField;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel ssnField;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JLabel typeField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
