package app;

import javax.swing.JOptionPane;

public class CreditCardForm extends javax.swing.JDialog {
    private Customer customer;
    private CreditCardsList cards;
    private DatabaseCommands data = new DatabaseCommands();

    public CreditCardForm(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        initComponents();
        cards = new CreditCardsList();
        this.customer = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditCardNumberLabel = new javax.swing.JLabel();
        firstFourNumbers = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        secondFourNumbers = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        thirdFourNumbers = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        fourthFourNumbers = new javax.swing.JTextField();
        addCardButton = new javax.swing.JButton();
        cardTypeLabel = new javax.swing.JLabel();
        cardTypeComboBox = new javax.swing.JComboBox();
        expirationDateLabel = new javax.swing.JLabel();
        expirationDateField = new javax.swing.JTextField();
        csvLabel = new javax.swing.JLabel();
        csvField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        creditCardNumberLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        creditCardNumberLabel.setText("Credit Card Number: ");

        firstFourNumbers.setToolTipText("");
        firstFourNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFourNumbersActionPerformed(evt);
            }
        });

        secondFourNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondFourNumbersActionPerformed(evt);
            }
        });

        thirdFourNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdFourNumbersActionPerformed(evt);
            }
        });

        fourthFourNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthFourNumbersActionPerformed(evt);
            }
        });

        addCardButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addCardButton.setText("Add Card");
        addCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardButtonActionPerformed(evt);
            }
        });

        cardTypeLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cardTypeLabel.setText("Card Type:");

        cardTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "MasterCard", "American Express", "Discover" }));
        cardTypeComboBox.setSelectedIndex(2);
        cardTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTypeComboBoxActionPerformed(evt);
            }
        });

        expirationDateLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        expirationDateLabel.setText("Expiration Date:");

        expirationDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expirationDateFieldActionPerformed(evt);
            }
        });

        csvLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        csvLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        csvLabel.setText("CSV:");

        csvField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creditCardNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstFourNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(secondFourNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thirdFourNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fourthFourNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(cardTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addCardButton))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(csvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(expirationDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(csvField)
                            .addComponent(expirationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditCardNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secondFourNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fourthFourNumbers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(thirdFourNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstFourNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardTypeLabel)
                    .addComponent(cardTypeComboBox)
                    .addComponent(expirationDateLabel)
                    .addComponent(expirationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(csvLabel)
                        .addComponent(csvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        firstFourNumbers.setDocument
        (new JTextFieldLimit(4));
        secondFourNumbers.setDocument
        (new JTextFieldLimit(4));
        thirdFourNumbers.setDocument
        (new JTextFieldLimit(4));
        fourthFourNumbers.setDocument(new JTextFieldLimit(4));
        expirationDateField.setDocument(new JTextFieldLimit(5));
        csvField.setDocument(new JTextFieldLimit(3));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstFourNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFourNumbersActionPerformed

    }//GEN-LAST:event_firstFourNumbersActionPerformed

    private void secondFourNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondFourNumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondFourNumbersActionPerformed

    private void thirdFourNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdFourNumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdFourNumbersActionPerformed

    private void fourthFourNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthFourNumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourthFourNumbersActionPerformed

    private void addCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardButtonActionPerformed
        StringBuilder errorMessage = new StringBuilder();
        String fNumbers = firstFourNumbers.getText(), sNumbers = secondFourNumbers.getText(), tNumbers = thirdFourNumbers.getText(),
                foNumbers = fourthFourNumbers.getText(), cardType = cardTypeComboBox.getSelectedItem().toString(),
                expirationDate = expirationDateField.getText(), csvNumber = csvField.getText();
        String number = fNumbers + sNumbers + tNumbers + foNumbers;
        long ccNumber = 0;
        boolean validCard = false;

        try {
            ccNumber = Long.parseLong(number);
            validCard = confirmCard(ccNumber);
            if(validCard){
                System.out.println(ccNumber + " is a valid card.");
            }else{
                errorMessage.append("Not a valid credit card.\n");
                System.out.println(ccNumber + " is not a valid card.");
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        if (!expirationDateField.getText().matches("\\d{2}[/]\\d{2}")) {
            errorMessage.append("Expiration date is incorrect e.g(mm/yy)");
        }
        int csvNum = Integer.parseInt(csvNumber);

        
        if (errorMessage.length() > 0) {
            JOptionPane.showMessageDialog(this, errorMessage.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
        }else{
            CreditCards card = new CreditCards(ccNumber, expirationDate, csvNum, cardType);
            data.queryCreditCardsTable(card, customer.getAccount().getAccountNumber());
            this.dispose();
        }
    }//GEN-LAST:event_addCardButtonActionPerformed

    private void expirationDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expirationDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expirationDateFieldActionPerformed

    private void csvFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csvFieldActionPerformed

    private void cardTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTypeComboBoxActionPerformed

    private static boolean confirmCard(long l) {
        int[] digits = Long.toString(l).chars().map(c -> c -= '0').toArray();
        String cardType = cardType(digits[0]);
        int len = digits.length;
        int even = 0;
        int odd = 0;
        int sum = 0;
        for (int i = len - 2; i >= 0; i -= 2) {
            if (digits[i] * 2 < 10) {
                even += digits[i] * 2;
            } else if (digits[i] * 2 >= 10) {
                even += arr(digits[i]);
            }
        }
        for (int i = len - 1; i >= 0; i -= 2) {
            odd += digits[i];
        }
        sum = odd + even;
        if (sum % 10 == 0) {
            System.out.println("Card is valid!");
            System.out.println("Card Type: " + cardType);
            return true;
        } else {
            System.out.println("Card is invalid!");
        }
        return false;
    }

    
    public static String cardType(int n) {
        
        /* Regex
        Visa: ^4[0-9]{12}(?:[0-9]{3})?$ All Visa card numbers start with a 4. New cards have 16 digits. Old cards have 13.
        MasterCard: ^5[1-5][0-9]{14}$ All MasterCard numbers start with the numbers 51 through 55. All have 16 digits.
        American Express: ^3[47][0-9]{13}$ American Express card numbers start with 34 or 37 and have 15 digits.
        Discover: ^6(?:011|5[0-9]{2})[0-9]{12}$ Discover card numbers begin with 6011 or 65. All have 16 digits.
        */

        if (n == 4) {
            return "Visa";
        } else if (n == 5) {
            return "Mastercard";
        } else if (n == 3) {
            return "American Express";
        } else {
            return null;
        }
    }

    public static int arr(int i) {
        if (i == 5) {
            return 1;
        } else if (i == 6) {
            return 3;
        } else if (i == 7) {
            return 5;
        } else if (i == 8) {
            return 7;
        } else if (i == 9) {
            return 9;
        } else {
            return 0;
        }
    }

    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreditCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreditCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreditCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreditCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CreditCardForm dialog = new CreditCardForm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCardButton;
    private javax.swing.JComboBox cardTypeComboBox;
    private javax.swing.JLabel cardTypeLabel;
    private javax.swing.JLabel creditCardNumberLabel;
    private javax.swing.JTextField csvField;
    private javax.swing.JLabel csvLabel;
    private javax.swing.JTextField expirationDateField;
    private javax.swing.JLabel expirationDateLabel;
    private javax.swing.JTextField firstFourNumbers;
    private javax.swing.JTextField fourthFourNumbers;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField secondFourNumbers;
    private javax.swing.JTextField thirdFourNumbers;
    // End of variables declaration//GEN-END:variables
}
