/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import javax.swing.JOptionPane;

/**
 *
 * @author Osiris Robledo
 */
public class WithdrawalMenu extends javax.swing.JDialog {
    private final Customer customer;
    private Bank bank = new Bank();
    private DatabaseCommands data = new DatabaseCommands();

    /**
     * Creates new form DepositMenu
     */
    public WithdrawalMenu(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.customer = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        withdrawalButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deposit Menu");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel1.setText("Withdrawal Amount:");
        getContentPane().add(jLabel1);
        getContentPane().add(amountField);

        withdrawalButton.setText("Withdrawal");
        withdrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawalButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalButtonActionPerformed
        StringBuilder warnings = new StringBuilder();
        //Verify the deposit is not empty
        if(amountField.getText().isEmpty()){
            warnings.append("Withdrawal amount is required.");
        }
        else {
            double amount = 0;
            try{
                amount = Double.parseDouble(amountField.getText());
                int result = JOptionPane.showConfirmDialog(this, "Withdraw $" + amount + " to the account?");
                if(result == JOptionPane.OK_OPTION){
                    double deposit = customer.getAccount().getBalance() - amount;
                    customer.getAccount().setBalance(deposit);
                    bank.accountMoneyQuery(customer, deposit);
                    data.populateActivityRows(customer, "Withdrawal", amount);
                    this.dispose();
                }
            } catch (NumberFormatException ex){
                warnings.append("Invalid amount");
            }
        }
        if(warnings.length() > 0){
            JOptionPane.showMessageDialog(this, warnings.toString(), "Withdrawal Waring", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_withdrawalButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton withdrawalButton;
    // End of variables declaration//GEN-END:variables
}
